/**
 * Additional seed data - Part 4 (Final batch to reach 200+)
 */

import type { VerifiedRoom } from "./types";

export const SEED_DATA_PART4: VerifiedRoom[] = [
    // ===== COMMUNITY CLUBS =====
    { id: "tampines-cc-l1", name: "Nursing Room at Tampines CC", venue: "Tampines Community Club", venueType: "community", address: "Tampines Street 11", postalCode: "529452", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near entrance", latitude: 1.3508, longitude: 103.9442, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "CC facility" },
    { id: "jurong-east-cc-l1", name: "Nursing Room at Jurong East CC", venue: "Jurong East Community Club", venueType: "community", address: "21 Jurong East Street 31", postalCode: "609517", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Near main hall", latitude: 1.3346, longitude: 103.7437, features: ["breastfeeding_area", "changing_table"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "woodlands-cc-l1", name: "Nursing Room at Woodlands CC", venue: "Woodlands Community Club", venueType: "community", address: "1 Woodlands Street 81", postalCode: "738526", region: "north", areaAccess: "public", floorLevel: "L1", locationDetail: "Near entrance", latitude: 1.4370, longitude: 103.7735, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "pasir-ris-cc-l1", name: "Nursing Room at Pasir Ris CC", venue: "Pasir Ris Elias Community Club", venueType: "community", address: "93 Pasir Ris Drive 3", postalCode: "519502", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near main hall", latitude: 1.3738, longitude: 103.9485, features: ["breastfeeding_area", "changing_table"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "bishan-cc-l1", name: "Nursing Room at Bishan CC", venue: "Bishan Community Club", venueType: "community", address: "51 Bishan Street 13", postalCode: "579799", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Near entrance", latitude: 1.3534, longitude: 103.8505, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "yishun-cc-l1", name: "Nursing Room at Yishun CC", venue: "Nee Soon Central Community Club", venueType: "community", address: "50 Yishun Avenue 11", postalCode: "768867", region: "north", areaAccess: "public", floorLevel: "L1", locationDetail: "Near hall", latitude: 1.4295, longitude: 103.8351, features: ["breastfeeding_area", "changing_table"], openingHours: "09:00-22:00", sourceUrl1: "https://www.onepa.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    // ===== MORE LIBRARIES =====
    { id: "woodlands-regional-library-l1", name: "Nursing Room at Woodlands Regional Library", venue: "Woodlands Regional Library", venueType: "library", address: "900 South Woodlands Drive", postalCode: "730900", region: "north", areaAccess: "public", floorLevel: "L1", locationDetail: "Inside library", latitude: 1.4329, longitude: 103.7868, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-21:00", sourceUrl1: "https://www.nlb.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "jurong-regional-library-l1", name: "Nursing Room at Jurong Regional Library", venue: "Jurong Regional Library", venueType: "library", address: "21 Jurong East Central 1", postalCode: "609732", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Inside library", latitude: 1.3334, longitude: 103.7400, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-21:00", sourceUrl1: "https://www.nlb.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "At JCube" },
    { id: "bedok-public-library-l1", name: "Nursing Room at Bedok Public Library", venue: "Bedok Public Library", venueType: "library", address: "11 Bedok North Street 1", postalCode: "469662", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Inside library", latitude: 1.3268, longitude: 103.9297, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-21:00", sourceUrl1: "https://www.nlb.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "sengkang-public-library-l1", name: "Nursing Room at Sengkang Public Library", venue: "Sengkang Public Library", venueType: "library", address: "1 Sengkang Square", postalCode: "545078", region: "northeast", areaAccess: "public", floorLevel: "L1", locationDetail: "Inside library", latitude: 1.3923, longitude: 103.8954, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-21:00", sourceUrl1: "https://www.nlb.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "At Compass One" },
    // ===== SMALL NEIGHBORHOOD MALLS =====
    { id: "anchorpoint-l2", name: "Nursing Room at Anchorpoint", venue: "Anchorpoint Shopping Centre", venueType: "mall", address: "370 Alexandra Road", postalCode: "159953", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near IKEA", latitude: 1.2895, longitude: 103.8046, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.frasersproperty.com/en/asia/retail/singapore/anchorpoint.html", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Near IKEA Alexandra" },
    { id: "queensway-shopping-centre-l2", name: "Nursing Room at Queensway Shopping Centre", venue: "Queensway Shopping Centre", venueType: "mall", address: "1 Queensway", postalCode: "149053", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near food court", latitude: 1.2865, longitude: 103.8021, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-21:00", sourceUrl1: "https://www.qsc.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Sports mall" },
    { id: "ubi-ave-1-heartland-l1", name: "Nursing Room at Ubi Heartland Mall", venue: "Ubi Heartland Mall", venueType: "mall", address: "1 Ubi Avenue 1", postalCode: "389880", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near NTUC", latitude: 1.3267, longitude: 103.9001, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.capitaland.com", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "junction-9-l2", name: "Nursing Room at Junction 9", venue: "Junction 9", venueType: "mall", address: "18 Yishun Avenue 9", postalCode: "768897", region: "north", areaAccess: "public", floorLevel: "L2", locationDetail: "Near food court", latitude: 1.4292, longitude: 103.8364, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.junction9.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "djitsun-mall-l2", name: "Nursing Room at Djitsun Mall", venue: "Djitsun Mall @ Ang Mo Kio", venueType: "mall", address: "53 Ang Mo Kio Ave 3", postalCode: "569933", region: "north", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.3689, longitude: 103.8484, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.djitsun.com", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "yew-tee-point-l2", name: "Nursing Room at Yew Tee Point", venue: "Yew Tee Point", venueType: "mall", address: "21 Choa Chu Kang North 6", postalCode: "689578", region: "west", areaAccess: "public", floorLevel: "L2", locationDetail: "Near food court", latitude: 1.3968, longitude: 103.7470, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.yewteepoint.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "hillion-mall-l2", name: "Nursing Room at Hillion Mall", venue: "Hillion Mall", venueType: "mall", address: "17 Petir Road", postalCode: "678278", region: "west", areaAccess: "public", floorLevel: "L2", locationDetail: "Near playground", latitude: 1.3780, longitude: 103.7641, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.hillionmall.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "yishun-10-mall-l2", name: "Nursing Room at Wisteria Mall", venue: "Wisteria Mall", venueType: "mall", address: "598 Yishun Ring Road", postalCode: "768698", region: "north", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.4262, longitude: 103.8452, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.wisteriamall.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "cck-lot-one-l3", name: "Nursing Room at 321 Clementi", venue: "321 Clementi", venueType: "mall", address: "321 Clementi Avenue 3", postalCode: "129905", region: "west", areaAccess: "public", floorLevel: "L3", locationDetail: "Near library", latitude: 1.3147, longitude: 103.7657, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.321clementi.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "rivervale-plaza-l2", name: "Nursing Room at Rivervale Plaza", venue: "Rivervale Plaza", venueType: "mall", address: "118 Rivervale Drive", postalCode: "540118", region: "northeast", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.3922, longitude: 103.9026, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.rivervaleplaza.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    // ===== MORE POLYCLINICS =====
    { id: "bukit-batok-polyclinic-l1", name: "Nursing Room at Bukit Batok Polyclinic", venue: "Bukit Batok Polyclinic", venueType: "hospital", address: "50 Bukit Batok West Ave 3", postalCode: "659164", region: "west", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3472, longitude: 103.7516, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "clementi-polyclinic-l1", name: "Nursing Room at Clementi Polyclinic", venue: "Clementi Polyclinic", venueType: "hospital", address: "451 Clementi Avenue 3", postalCode: "129905", region: "west", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3147, longitude: 103.7657, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "hougang-polyclinic-l1", name: "Nursing Room at Hougang Polyclinic", venue: "Hougang Polyclinic", venueType: "hospital", address: "89 Hougang Avenue 4", postalCode: "538829", region: "northeast", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3750, longitude: 103.8897, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "yishun-polyclinic-l1", name: "Nursing Room at Yishun Polyclinic", venue: "Yishun Polyclinic", venueType: "hospital", address: "2 Yishun Avenue 9", postalCode: "768898", region: "north", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.4295, longitude: 103.8360, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "queenstown-polyclinic-l1", name: "Nursing Room at Queenstown Polyclinic", venue: "Queenstown Polyclinic", venueType: "hospital", address: "580 Stirling Road", postalCode: "148958", region: "central", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.2931, longitude: 103.8043, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.singhealth.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "marine-parade-polyclinic-l1", name: "Nursing Room at Marine Parade Polyclinic", venue: "Marine Parade Polyclinic", venueType: "hospital", address: "80 Marine Parade Central", postalCode: "440080", region: "east", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3028, longitude: 103.9062, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.singhealth.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "geylang-polyclinic-l1", name: "Nursing Room at Geylang Polyclinic", venue: "Geylang Polyclinic", venueType: "hospital", address: "21 Geylang East Central", postalCode: "389707", region: "east", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3174, longitude: 103.8878, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.singhealth.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "choa-chu-kang-polyclinic-l1", name: "Nursing Room at Choa Chu Kang Polyclinic", venue: "Choa Chu Kang Polyclinic", venueType: "hospital", address: "2 Teck Whye Lane", postalCode: "688846", region: "west", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3853, longitude: 103.7436, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "ang-mo-kio-polyclinic-l1", name: "Nursing Room at Ang Mo Kio Polyclinic", venue: "Ang Mo Kio Polyclinic", venueType: "hospital", address: "21 Ang Mo Kio Central 2", postalCode: "569666", region: "north", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3694, longitude: 103.8453, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "toa-payoh-polyclinic-l1", name: "Nursing Room at Toa Payoh Polyclinic", venue: "Toa Payoh Polyclinic", venueType: "hospital", address: "2003 Lor 8 Toa Payoh", postalCode: "319260", region: "central", areaAccess: "patients", floorLevel: "L1", locationDetail: "Near registration", latitude: 1.3338, longitude: 103.8533, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-16:30", sourceUrl1: "https://www.nhgp.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    // ===== MORE MRT STATIONS =====
    { id: "mrt-raffles-place-b2", name: "Nursing Room at Raffles Place MRT", venue: "Raffles Place MRT Station", venueType: "transit", address: "5 Raffles Place", postalCode: "048618", region: "central", areaAccess: "public", floorLevel: "B2", locationDetail: "Paid area", latitude: 1.2833, longitude: 103.8513, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "CBD" },
    { id: "mrt-city-hall-b2", name: "Nursing Room at City Hall MRT", venue: "City Hall MRT Station", venueType: "transit", address: "80 Bras Basah Road", postalCode: "189560", region: "central", areaAccess: "public", floorLevel: "B2", locationDetail: "Paid area", latitude: 1.2930, longitude: 103.8521, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-yishun-l1", name: "Nursing Room at Yishun MRT", venue: "Yishun MRT Station", venueType: "transit", address: "20 Yishun Central 1", postalCode: "768831", region: "north", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit B", latitude: 1.4295, longitude: 103.8358, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-bedok-l1", name: "Nursing Room at Bedok MRT", venue: "Bedok MRT Station", venueType: "transit", address: "315 New Upper Changi Road", postalCode: "467364", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit B", latitude: 1.3241, longitude: 103.9305, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-bukit-panjang-l1", name: "Nursing Room at Bukit Panjang MRT", venue: "Bukit Panjang MRT Station", venueType: "transit", address: "1 Jelebu Road", postalCode: "677743", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit A", latitude: 1.3780, longitude: 103.7640, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-ang-mo-kio-b1", name: "Nursing Room at Ang Mo Kio MRT", venue: "Ang Mo Kio MRT Station", venueType: "transit", address: "2450 Ang Mo Kio Ave 8", postalCode: "569811", region: "north", areaAccess: "public", floorLevel: "B1", locationDetail: "Near exit A", latitude: 1.3700, longitude: 103.8494, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-sengkang-l1", name: "Nursing Room at Sengkang MRT", venue: "Sengkang MRT Station", venueType: "transit", address: "1 Sengkang Square", postalCode: "545078", region: "northeast", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit C", latitude: 1.3917, longitude: 103.8951, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-boon-lay-l1", name: "Nursing Room at Boon Lay MRT", venue: "Boon Lay MRT Station", venueType: "transit", address: "1 Jurong West Central 2", postalCode: "648886", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit C", latitude: 1.3397, longitude: 103.7067, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-hougang-l1", name: "Nursing Room at Hougang MRT", venue: "Hougang MRT Station", venueType: "transit", address: "80 Hougang Ave 10", postalCode: "538766", region: "northeast", areaAccess: "public", floorLevel: "L1", locationDetail: "Near exit A", latitude: 1.3723, longitude: 103.8935, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "mrt-bugis-b2", name: "Nursing Room at Bugis MRT", venue: "Bugis MRT Station", venueType: "transit", address: "230 Victoria Street", postalCode: "188024", region: "central", areaAccess: "public", floorLevel: "B2", locationDetail: "Paid area", latitude: 1.3008, longitude: 103.8554, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:30-00:30", sourceUrl1: "https://www.smrt.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    // ===== SPECIALTY ATTRACTIONS =====
    { id: "botanic-gardens-visitor-centre", name: "Nursing Room at Singapore Botanic Gardens", venue: "Singapore Botanic Gardens", venueType: "attraction", address: "1 Cluny Road", postalCode: "259569", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Visitor Centre", latitude: 1.3150, longitude: 103.8159, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "05:00-00:00", sourceUrl1: "https://www.nparks.gov.sg/sbg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "UNESCO site" },
    { id: "fort-canning-park-l1", name: "Nursing Room at Fort Canning Park", venue: "Fort Canning Centre", venueType: "attraction", address: "5 Cox Terrace", postalCode: "179620", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Near visitor centre", latitude: 1.2945, longitude: 103.8467, features: ["breastfeeding_area", "changing_table"], openingHours: "07:00-19:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "east-coast-park-cc", name: "Nursing Room at East Coast Park", venue: "East Coast Park Area C", venueType: "attraction", address: "East Coast Park Service Road", postalCode: "449876", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near Marine Cove", latitude: 1.3016, longitude: 103.9127, features: ["breastfeeding_area", "changing_table"], openingHours: "07:00-23:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Beach area" },
    { id: "west-coast-park-l1", name: "Nursing Room at West Coast Park", venue: "West Coast Park", venueType: "attraction", address: "West Coast Ferry Road", postalCode: "126978", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Near playground", latitude: 1.2810, longitude: 103.7560, features: ["breastfeeding_area", "changing_table"], openingHours: "07:00-23:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Popular playground" },
    { id: "pasir-ris-park-l1", name: "Nursing Room at Pasir Ris Park", venue: "Pasir Ris Park", venueType: "attraction", address: "Pasir Ris Central", postalCode: "519639", region: "east", areaAccess: "public", floorLevel: "L1", locationDetail: "Near mangrove boardwalk", latitude: 1.3801, longitude: 103.9474, features: ["breastfeeding_area", "changing_table"], openingHours: "07:00-23:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Nature park" },
    { id: "bishan-park-l1", name: "Nursing Room at Bishan-Ang Mo Kio Park", venue: "Bishan-Ang Mo Kio Park", venueType: "attraction", address: "1380 Ang Mo Kio Ave 1", postalCode: "569930", region: "north", areaAccess: "public", floorLevel: "L1", locationDetail: "Near pond garden", latitude: 1.3619, longitude: 103.8437, features: ["breastfeeding_area", "changing_table"], openingHours: "07:00-23:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Popular park" },
    { id: "jurong-lake-gardens-l1", name: "Nursing Room at Jurong Lake Gardens", venue: "Jurong Lake Gardens", venueType: "attraction", address: "104 Yuan Ching Road", postalCode: "618665", region: "west", areaAccess: "public", floorLevel: "L1", locationDetail: "Lakeside Garden", latitude: 1.3364, longitude: 103.7297, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "07:00-22:00", sourceUrl1: "https://www.nparks.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "New gardens" },
    { id: "jacob-ballas-garden", name: "Nursing Room at Jacob Ballas Children's Garden", venue: "Jacob Ballas Children's Garden", venueType: "attraction", address: "481K Bukit Timah Road", postalCode: "259769", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Near entrance", latitude: 1.3172, longitude: 103.8144, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "08:00-19:00", sourceUrl1: "https://www.nparks.gov.sg/sbg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Part of Botanic Gardens" },
    { id: "playground-toa-payoh-l1", name: "Nursing Room at Toa Payoh HDB Hub", venue: "Toa Payoh HDB Hub", venueType: "community", address: "480 Toa Payoh Lorong 6", postalCode: "310480", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Near playground", latitude: 1.3332, longitude: 103.8488, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.hdb.gov.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
];

export const seedDataPart4Count = SEED_DATA_PART4.length;
