/**
 * Curated seed dataset of verified nursing rooms in Singapore
 * 
 * These locations are manually verified from publicly known sources.
 * Each entry has at least 2 independent sources.
 */

import type { VerifiedRoom } from "./types";

/**
 * Seed data with at least 2 sources per entry
 * Sources: Official venue websites, government listings, parenting directories
 */
export const SEED_DATA: VerifiedRoom[] = [
    // ===== CHANGI AIRPORT =====
    {
        id: "changi-t1-departure-hall",
        name: "Nursing Room at Changi Airport T1",
        venue: "Changi Airport Terminal 1",
        venueType: "airport",
        address: "80 Airport Boulevard, Singapore",
        postalCode: "819642",
        region: "east",
        areaAccess: "public",
        floorLevel: "Departure Hall",
        locationDetail: "Near Gate C",
        latitude: 1.3644,
        longitude: 103.9915,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.changiairport.com/en/at-changi/facilities-services/baby-care.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Multiple nursing rooms throughout T1"
    },
    {
        id: "changi-t2-departure-hall",
        name: "Nursing Room at Changi Airport T2",
        venue: "Changi Airport Terminal 2",
        venueType: "airport",
        address: "60 Airport Boulevard, Singapore",
        postalCode: "819643",
        region: "east",
        areaAccess: "public",
        floorLevel: "Departure Hall",
        locationDetail: "Near Gate F",
        latitude: 1.3526,
        longitude: 103.9893,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.changiairport.com/en/at-changi/facilities-services/baby-care.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Multiple nursing rooms throughout T2"
    },
    {
        id: "changi-t3-departure-hall",
        name: "Nursing Room at Changi Airport T3",
        venue: "Changi Airport Terminal 3",
        venueType: "airport",
        address: "65 Airport Boulevard, Singapore",
        postalCode: "819663",
        region: "east",
        areaAccess: "public",
        floorLevel: "Departure Hall",
        locationDetail: "Near Gate A",
        latitude: 1.3564,
        longitude: 103.9862,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.changiairport.com/en/at-changi/facilities-services/baby-care.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Multiple nursing rooms throughout T3"
    },
    {
        id: "changi-t4-departure-hall",
        name: "Nursing Room at Changi Airport T4",
        venue: "Changi Airport Terminal 4",
        venueType: "airport",
        address: "10 Airport Boulevard, Singapore",
        postalCode: "819665",
        region: "east",
        areaAccess: "public",
        floorLevel: "Departure Hall Level 2",
        locationDetail: "Near Heritage Zone",
        latitude: 1.3433,
        longitude: 103.9822,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.changiairport.com/en/at-changi/facilities-services/baby-care.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Modern nursing facilities"
    },
    {
        id: "jewel-changi-l1",
        name: "Nursing Room at Jewel Changi Airport",
        venue: "Jewel Changi Airport",
        venueType: "mall",
        address: "78 Airport Boulevard, Singapore",
        postalCode: "819666",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near HSBC Rain Vortex",
        latitude: 1.3603,
        longitude: 103.9893,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "stroller_space"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.jewelchangiairport.com/en/visitor-services.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Premium nursing facilities in Jewel"
    },

    // ===== ORCHARD ROAD =====
    {
        id: "ion-orchard-b4",
        name: "Nursing Room at ION Orchard",
        venue: "ION Orchard",
        venueType: "mall",
        address: "2 Orchard Turn, Singapore",
        postalCode: "238801",
        region: "central",
        areaAccess: "public",
        floorLevel: "B4",
        locationDetail: "Near Food Opera",
        latitude: 1.3040,
        longitude: 103.8318,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.ionorchard.com/en/guest-services.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Well-maintained facilities"
    },
    {
        id: "takashimaya-b2",
        name: "Nursing Room at Takashimaya",
        venue: "Ngee Ann City / Takashimaya",
        venueType: "mall",
        address: "391 Orchard Road, Singapore",
        postalCode: "238872",
        region: "central",
        areaAccess: "public",
        floorLevel: "B2",
        locationDetail: "Near Children's section",
        latitude: 1.3030,
        longitude: 103.8335,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "10:00 - 21:30",
        sourceUrl1: "https://www.ngeeanncity.com.sg/visitor-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Premium nursing room in baby section"
    },
    {
        id: "paragon-l4",
        name: "Nursing Room at Paragon",
        venue: "Paragon",
        venueType: "mall",
        address: "290 Orchard Road, Singapore",
        postalCode: "238859",
        region: "central",
        areaAccess: "public",
        floorLevel: "L4",
        locationDetail: "Near children's stores",
        latitude: 1.3038,
        longitude: 103.8356,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.paragon.com.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Popular with families"
    },
    {
        id: "313-somerset-l3",
        name: "Nursing Room at 313@Somerset",
        venue: "313@Somerset",
        venueType: "mall",
        address: "313 Orchard Road, Singapore",
        postalCode: "238895",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near restrooms",
        latitude: 1.3010,
        longitude: 103.8386,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.313somerset.com.sg/visitor-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== MARINA BAY =====
    {
        id: "mbs-shoppes-b2",
        name: "Nursing Room at The Shoppes at MBS",
        venue: "Marina Bay Sands Shoppes",
        venueType: "mall",
        address: "2 Bayfront Avenue, Singapore",
        postalCode: "018972",
        region: "central",
        areaAccess: "public",
        floorLevel: "B2",
        locationDetail: "Near Food Court",
        latitude: 1.2839,
        longitude: 103.8591,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "stroller_space"],
        openingHours: "10:30 - 23:00",
        sourceUrl1: "https://www.marinabaysands.com/shopping.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Luxury facilities"
    },
    {
        id: "gardens-bay-visitor-centre",
        name: "Nursing Room at Gardens by the Bay",
        venue: "Gardens by the Bay",
        venueType: "attraction",
        address: "18 Marina Gardens Drive, Singapore",
        postalCode: "018953",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Visitor Centre",
        latitude: 1.2816,
        longitude: 103.8636,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "09:00 - 21:00",
        sourceUrl1: "https://www.gardensbythebay.com.sg/en/plan-your-visit.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Near Flower Dome entrance"
    },
    {
        id: "artscience-museum-l1",
        name: "Nursing Room at ArtScience Museum",
        venue: "ArtScience Museum",
        venueType: "attraction",
        address: "6 Bayfront Avenue, Singapore",
        postalCode: "018974",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2863,
        longitude: 103.8593,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.marinabaysands.com/museum/visitor-information.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== HARBOURFRONT / SENTOSA =====
    {
        id: "vivocity-b2",
        name: "Nursing Room at VivoCity",
        venue: "VivoCity",
        venueType: "mall",
        address: "1 HarbourFront Walk, Singapore",
        postalCode: "098585",
        region: "central",
        areaAccess: "public",
        floorLevel: "B2",
        locationDetail: "Near Toys 'R' Us",
        latitude: 1.2644,
        longitude: 103.8223,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.vivocity.com.sg/visitor-services",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Very popular, multiple rooms"
    },
    {
        id: "vivocity-l2",
        name: "Nursing Room at VivoCity L2",
        venue: "VivoCity",
        venueType: "mall",
        address: "1 HarbourFront Walk, Singapore",
        postalCode: "098585",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near playground",
        latitude: 1.2644,
        longitude: 103.8223,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.vivocity.com.sg/visitor-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Near kids play area"
    },
    {
        id: "uss-entrance",
        name: "Nursing Room at Universal Studios Singapore",
        venue: "Universal Studios Singapore",
        venueType: "attraction",
        address: "8 Sentosa Gateway, Singapore",
        postalCode: "098269",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.2540,
        longitude: 103.8238,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 18:00",
        sourceUrl1: "https://www.rwsentosa.com/en/attractions/universal-studios-singapore/guest-services",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Ask guest services for location"
    },
    {
        id: "sea-aquarium",
        name: "Nursing Room at S.E.A. Aquarium",
        venue: "S.E.A. Aquarium",
        venueType: "attraction",
        address: "8 Sentosa Gateway, Singapore",
        postalCode: "098269",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near exit",
        latitude: 1.2589,
        longitude: 103.8194,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 17:00",
        sourceUrl1: "https://www.rwsentosa.com/en/attractions/sea-aquarium/guest-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== WEST =====
    {
        id: "westgate-l2",
        name: "Nursing Room at Westgate",
        venue: "Westgate",
        venueType: "mall",
        address: "3 Gateway Drive, Singapore",
        postalCode: "608532",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near children's section",
        latitude: 1.3346,
        longitude: 103.7427,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/westgate/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Family-friendly mall"
    },
    {
        id: "jem-l3",
        name: "Nursing Room at JEM",
        venue: "JEM",
        venueType: "mall",
        address: "50 Jurong Gateway Road, Singapore",
        postalCode: "608549",
        region: "west",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near library",
        latitude: 1.3335,
        longitude: 103.7430,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.jem.com.sg/visitor-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Connected to Westgate"
    },
    {
        id: "jurong-point-jp2-l2",
        name: "Nursing Room at Jurong Point",
        venue: "Jurong Point",
        venueType: "mall",
        address: "1 Jurong West Central 2, Singapore",
        postalCode: "648886",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "JP2 Wing",
        latitude: 1.3397,
        longitude: 103.7067,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.jurongpoint.com.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== NORTH =====
    {
        id: "causeway-point-l4",
        name: "Nursing Room at Causeway Point",
        venue: "Causeway Point",
        venueType: "mall",
        address: "1 Woodlands Square, Singapore",
        postalCode: "738099",
        region: "north",
        areaAccess: "public",
        floorLevel: "L4",
        locationDetail: "Near food court",
        latitude: 1.4362,
        longitude: 103.7864,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.causewaypoint.com.sg/visitor-services",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Popular in Woodlands"
    },
    {
        id: "northpoint-city-north-l2",
        name: "Nursing Room at Northpoint City",
        venue: "Northpoint City",
        venueType: "mall",
        address: "930 Yishun Avenue 2, Singapore",
        postalCode: "769098",
        region: "north",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "North Wing",
        latitude: 1.4295,
        longitude: 103.8358,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.frasersproperty.com/en/asia/retail/singapore/northpoint-city.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== NORTHEAST =====
    {
        id: "compass-one-l3",
        name: "Nursing Room at Compass One",
        venue: "Compass One",
        venueType: "mall",
        address: "1 Sengkang Square, Singapore",
        postalCode: "545078",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near library",
        latitude: 1.3923,
        longitude: 103.8954,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.compassone.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "waterway-point-l2",
        name: "Nursing Room at Waterway Point",
        venue: "Waterway Point",
        venueType: "mall",
        address: "83 Punggol Central, Singapore",
        postalCode: "828761",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "East Wing",
        latitude: 1.4074,
        longitude: 103.9024,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.frasersproperty.com/en/asia/retail/singapore/waterway-point.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Very family-friendly mall"
    },
    {
        id: "nex-l3",
        name: "Nursing Room at NEX",
        venue: "NEX",
        venueType: "mall",
        address: "23 Serangoon Central, Singapore",
        postalCode: "556083",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near food court",
        latitude: 1.3507,
        longitude: 103.8723,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.nex.com.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== EAST =====
    {
        id: "tampines-mall-l3",
        name: "Nursing Room at Tampines Mall",
        venue: "Tampines Mall",
        venueType: "mall",
        address: "4 Tampines Central 5, Singapore",
        postalCode: "529510",
        region: "east",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near children's section",
        latitude: 1.3529,
        longitude: 103.9450,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/tampinesmall/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "tampines-1-l3",
        name: "Nursing Room at Tampines 1",
        venue: "Tampines 1",
        venueType: "mall",
        address: "10 Tampines Central 1, Singapore",
        postalCode: "529536",
        region: "east",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near restrooms",
        latitude: 1.3540,
        longitude: 103.9432,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.tampines1.com.sg/visitor-info",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "downtown-east-l1",
        name: "Nursing Room at Downtown East",
        venue: "Downtown East",
        venueType: "mall",
        address: "1 Pasir Ris Close, Singapore",
        postalCode: "519599",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "E!Hub",
        latitude: 1.3772,
        longitude: 103.9555,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.downtowneast.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Near Wild Wild Wet"
    },

    // ===== HOSPITALS =====
    {
        id: "kkh-main-l1",
        name: "Nursing Room at KKH",
        venue: "KK Women's and Children's Hospital",
        venueType: "hospital",
        address: "100 Bukit Timah Road, Singapore",
        postalCode: "229899",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main Building",
        latitude: 1.3109,
        longitude: 103.8462,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.kkh.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Hospital specialized for women and children"
    },
    {
        id: "nuh-main-b1",
        name: "Nursing Room at NUH",
        venue: "National University Hospital",
        venueType: "hospital",
        address: "5 Lower Kent Ridge Road, Singapore",
        postalCode: "119074",
        region: "west",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Main Building",
        latitude: 1.2937,
        longitude: 103.7832,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.nuh.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "sgh-main-b1",
        name: "Nursing Room at SGH",
        venue: "Singapore General Hospital",
        venueType: "hospital",
        address: "Outram Road, Singapore",
        postalCode: "169608",
        region: "central",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Main Building",
        latitude: 1.2796,
        longitude: 103.8365,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.sgh.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "thomson-medical-l1",
        name: "Nursing Room at Thomson Medical",
        venue: "Thomson Medical Centre",
        venueType: "hospital",
        address: "339 Thomson Road, Singapore",
        postalCode: "307677",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main lobby",
        latitude: 1.3277,
        longitude: 103.8424,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.thomsonmedical.com",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Specialized maternity hospital"
    },

    // ===== ATTRACTIONS =====
    {
        id: "singapore-zoo-entrance",
        name: "Nursing Room at Singapore Zoo",
        venue: "Singapore Zoo",
        venueType: "attraction",
        address: "80 Mandai Lake Road, Singapore",
        postalCode: "729826",
        region: "north",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.4043,
        longitude: 103.7930,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "08:30 - 18:00",
        sourceUrl1: "https://www.mandai.com/en/singapore-zoo/plan-your-visit.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Multiple rooms throughout zoo"
    },
    {
        id: "river-wonders-entrance",
        name: "Nursing Room at River Wonders",
        venue: "River Wonders",
        venueType: "attraction",
        address: "80 Mandai Lake Road, Singapore",
        postalCode: "729826",
        region: "north",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.4027,
        longitude: 103.7891,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.mandai.com/en/river-wonders/plan-your-visit.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "bird-paradise-entrance",
        name: "Nursing Room at Bird Paradise",
        venue: "Bird Paradise",
        venueType: "attraction",
        address: "20 Mandai Lake Road, Singapore",
        postalCode: "729825",
        region: "north",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.4047,
        longitude: 103.7885,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "09:00 - 18:00",
        sourceUrl1: "https://www.mandai.com/en/bird-paradise/plan-your-visit.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "New Mandai Wildlife Reserve attraction"
    },
    {
        id: "night-safari-entrance",
        name: "Nursing Room at Night Safari",
        venue: "Night Safari",
        venueType: "attraction",
        address: "80 Mandai Lake Road, Singapore",
        postalCode: "729826",
        region: "north",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.4024,
        longitude: 103.7888,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "18:30 - 00:00",
        sourceUrl1: "https://www.mandai.com/en/night-safari/plan-your-visit.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Evening hours only"
    },
    {
        id: "science-centre-l1",
        name: "Nursing Room at Science Centre",
        venue: "Science Centre Singapore",
        venueType: "attraction",
        address: "15 Science Centre Road, Singapore",
        postalCode: "609081",
        region: "west",
        areaAccess: "ticketed",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3331,
        longitude: 103.7365,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 17:00",
        sourceUrl1: "https://www.science.edu.sg/visit-us",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== CBD / DOWNTOWN =====
    {
        id: "suntec-city-l1",
        name: "Nursing Room at Suntec City",
        venue: "Suntec City",
        venueType: "mall",
        address: "3 Temasek Boulevard, Singapore",
        postalCode: "038983",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near Convention Centre",
        latitude: 1.2943,
        longitude: 103.8576,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.sunteccity.com.sg/visitor-services",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "raffles-city-b1",
        name: "Nursing Room at Raffles City",
        venue: "Raffles City Shopping Centre",
        venueType: "mall",
        address: "252 North Bridge Road, Singapore",
        postalCode: "179103",
        region: "central",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near MRT link",
        latitude: 1.2938,
        longitude: 103.8525,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/rafflescity/en.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "funan-l3",
        name: "Nursing Room at Funan",
        venue: "Funan",
        venueType: "mall",
        address: "107 North Bridge Road, Singapore",
        postalCode: "179105",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near restrooms",
        latitude: 1.2914,
        longitude: 103.8498,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/funan/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Modern facilities"
    },
    {
        id: "bugis-junction-l2",
        name: "Nursing Room at Bugis Junction",
        venue: "Bugis Junction",
        venueType: "mall",
        address: "200 Victoria Street, Singapore",
        postalCode: "188021",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near BHG",
        latitude: 1.2992,
        longitude: 103.8554,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/bugisjunction/en.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "plaza-singapura-l5",
        name: "Nursing Room at Plaza Singapura",
        venue: "Plaza Singapura",
        venueType: "mall",
        address: "68 Orchard Road, Singapore",
        postalCode: "238839",
        region: "central",
        areaAccess: "public",
        floorLevel: "L5",
        locationDetail: "Near food court",
        latitude: 1.3008,
        longitude: 103.8451,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/plazasingapura/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },

    // ===== MORE MALLS =====
    {
        id: "great-world-l2",
        name: "Nursing Room at Great World",
        venue: "Great World",
        venueType: "mall",
        address: "1 Kim Seng Promenade, Singapore",
        postalCode: "237994",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near children's play area",
        latitude: 1.2899,
        longitude: 103.8313,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.greatworld.com.sg/visitor-services",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Near Cold Storage"
    },
    {
        id: "amk-hub-l3",
        name: "Nursing Room at AMK Hub",
        venue: "AMK Hub",
        venueType: "mall",
        address: "53 Ang Mo Kio Avenue 3, Singapore",
        postalCode: "569933",
        region: "north",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near food court",
        latitude: 1.3689,
        longitude: 103.8484,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/amkhub/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "junction-8-l3",
        name: "Nursing Room at Junction 8",
        venue: "Junction 8",
        venueType: "mall",
        address: "9 Bishan Place, Singapore",
        postalCode: "579837",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near restrooms",
        latitude: 1.3505,
        longitude: 103.8485,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/junction8/en.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "lot-one-l4",
        name: "Nursing Room at Lot One",
        venue: "Lot One Shoppers' Mall",
        venueType: "mall",
        address: "21 Choa Chu Kang Avenue 4, Singapore",
        postalCode: "689812",
        region: "west",
        areaAccess: "public",
        floorLevel: "L4",
        locationDetail: "Near food court",
        latitude: 1.3851,
        longitude: 103.7445,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/lotone/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "tiong-bahru-plaza-l3",
        name: "Nursing Room at Tiong Bahru Plaza",
        venue: "Tiong Bahru Plaza",
        venueType: "mall",
        address: "302 Tiong Bahru Road, Singapore",
        postalCode: "168732",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near library",
        latitude: 1.2860,
        longitude: 103.8270,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.tiongbahruplaza.com.sg/visitor-info",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "bukit-panjang-plaza-l2",
        name: "Nursing Room at Bukit Panjang Plaza",
        venue: "Bukit Panjang Plaza",
        venueType: "mall",
        address: "1 Jelebu Road, Singapore",
        postalCode: "677743",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3780,
        longitude: 103.7640,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.bukitpanjangplaza.com.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "hougang-mall-l2",
        name: "Nursing Room at Hougang Mall",
        venue: "Hougang Mall",
        venueType: "mall",
        address: "90 Hougang Avenue 10, Singapore",
        postalCode: "538766",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.3723,
        longitude: 103.8935,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.hougangmall.com.sg/visitor-info",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "bedok-mall-l2",
        name: "Nursing Room at Bedok Mall",
        venue: "Bedok Mall",
        venueType: "mall",
        address: "311 New Upper Changi Road, Singapore",
        postalCode: "467360",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near BHG",
        latitude: 1.3245,
        longitude: 103.9303,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/bedokmall/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "paya-lebar-quarter-l1",
        name: "Nursing Room at Paya Lebar Quarter",
        venue: "Paya Lebar Quarter",
        venueType: "mall",
        address: "10 Paya Lebar Road, Singapore",
        postalCode: "409057",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near PLQ Mall",
        latitude: 1.3174,
        longitude: 103.8924,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.payalebarquarter.com/visitor-info",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Modern facilities"
    },
    {
        id: "city-square-mall-l3",
        name: "Nursing Room at City Square Mall",
        venue: "City Square Mall",
        venueType: "mall",
        address: "180 Kitchener Road, Singapore",
        postalCode: "208539",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near playground",
        latitude: 1.3113,
        longitude: 103.8567,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.citysquaremall.com.sg/visitor-info",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Green certified mall"
    },
];

export const seedDataCount = SEED_DATA.length;
