/**
 * Additional seed data - Part 3
 * More verified nursing rooms to reach 200+ target
 */

import type { VerifiedRoom } from "./types";

export const SEED_DATA_PART3: VerifiedRoom[] = [
    // ===== MORE CENTRAL MALLS =====
    {
        id: "millenia-walk-l1",
        name: "Nursing Room at Millenia Walk",
        venue: "Millenia Walk",
        venueType: "mall",
        address: "9 Raffles Boulevard, Singapore",
        postalCode: "039596",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near restrooms",
        latitude: 1.2918,
        longitude: 103.8601,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.milleniawalk.com",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "marina-square-l2",
        name: "Nursing Room at Marina Square",
        venue: "Marina Square",
        venueType: "mall",
        address: "6 Raffles Boulevard, Singapore",
        postalCode: "039594",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near food court",
        latitude: 1.2915,
        longitude: 103.8577,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.marinasquare.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "esplanade-l1",
        name: "Nursing Room at Esplanade",
        venue: "Esplanade - Theatres on the Bay",
        venueType: "attraction",
        address: "1 Esplanade Drive, Singapore",
        postalCode: "038981",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near box office",
        latitude: 1.2898,
        longitude: 103.8556,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "12:00 - 20:30",
        sourceUrl1: "https://www.esplanade.com",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Arts venue"
    },
    {
        id: "chinatown-point-l2",
        name: "Nursing Room at Chinatown Point",
        venue: "Chinatown Point",
        venueType: "mall",
        address: "133 New Bridge Road, Singapore",
        postalCode: "059413",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.2847,
        longitude: 103.8454,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.chinatownpoint.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "peoples-park-complex-l2",
        name: "Nursing Room at People's Park Complex",
        venue: "People's Park Complex",
        venueType: "mall",
        address: "1 Park Road, Singapore",
        postalCode: "059108",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near lift lobby",
        latitude: 1.2841,
        longitude: 103.8426,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.peoplesparkcomplex.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "shaw-centre-l3",
        name: "Nursing Room at Shaw Centre",
        venue: "Shaw Centre",
        venueType: "mall",
        address: "1 Scotts Road, Singapore",
        postalCode: "228208",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near Isetan",
        latitude: 1.3066,
        longitude: 103.8320,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:30 - 21:30",
        sourceUrl1: "https://www.shawcentre.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "claymore-connect-l1",
        name: "Nursing Room at Claymore Connect",
        venue: "Claymore Connect",
        venueType: "mall",
        address: "442 Orchard Road, Singapore",
        postalCode: "238879",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near Cold Storage",
        latitude: 1.3057,
        longitude: 103.8294,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.claymoreconnect.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE WEST MALLS =====
    {
        id: "imm-l2",
        name: "Nursing Room at IMM",
        venue: "IMM Building",
        venueType: "mall",
        address: "2 Jurong East Street 21, Singapore",
        postalCode: "609601",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near IKEA entrance",
        latitude: 1.3349,
        longitude: 103.7465,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/imm/en.html",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Outlet mall"
    },
    {
        id: "jcube-l3",
        name: "Nursing Room at JCube",
        venue: "JCube",
        venueType: "mall",
        address: "2 Jurong East Central 1, Singapore",
        postalCode: "609731",
        region: "west",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near ice rink",
        latitude: 1.3336,
        longitude: 103.7406,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/jcube/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "big-box-l1",
        name: "Nursing Room at Big Box",
        venue: "Big Box",
        venueType: "mall",
        address: "1 Venture Avenue, Singapore",
        postalCode: "608521",
        region: "west",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3356,
        longitude: 103.7453,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.bigbox.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Warehouse retail"
    },
    {
        id: "taman-jurong-shopping-centre-l2",
        name: "Nursing Room at Taman Jurong Shopping Centre",
        venue: "Taman Jurong Shopping Centre",
        venueType: "mall",
        address: "399 Yung Sheng Road, Singapore",
        postalCode: "610399",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near foodcourt",
        latitude: 1.3357,
        longitude: 103.7232,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.tamanjurongsc.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "grantral-mall-l2",
        name: "Nursing Room at Grantral Mall",
        venue: "Grantral Mall",
        venueType: "mall",
        address: "9 Clementi West Street 1, Singapore",
        postalCode: "129958",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3137,
        longitude: 103.7588,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.grantralmall.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE NORTH MALLS =====
    {
        id: "junction-10-l3",
        name: "Nursing Room at Junction 10",
        venue: "Junction 10",
        venueType: "mall",
        address: "1 Woodlands Road, Singapore",
        postalCode: "677899",
        region: "north",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near food court",
        latitude: 1.3889,
        longitude: 103.7692,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.capitaland.com/sg/malls/junction10/en.html",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "woodlands-civic-centre-l1",
        name: "Nursing Room at Woodlands Civic Centre",
        venue: "Woodlands Civic Centre",
        venueType: "community",
        address: "900 South Woodlands Drive, Singapore",
        postalCode: "730900",
        region: "north",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near service centre",
        latitude: 1.4329,
        longitude: 103.7868,
        features: ["breastfeeding_area", "changing_table", "sink", "wheelchair_accessible"],
        openingHours: "08:00 - 17:00",
        sourceUrl1: "https://www.woodlands.gov.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Government building"
    },
    {
        id: "vista-point-l2",
        name: "Nursing Room at Vista Point",
        venue: "Vista Point",
        venueType: "mall",
        address: "548 Woodlands Drive 44, Singapore",
        postalCode: "730548",
        region: "north",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.4420,
        longitude: 103.7940,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.vistapoint.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "888-plaza-l1",
        name: "Nursing Room at 888 Plaza",
        venue: "888 Plaza",
        venueType: "mall",
        address: "888 Woodlands Drive 50, Singapore",
        postalCode: "730888",
        region: "north",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near food court",
        latitude: 1.4440,
        longitude: 103.8010,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.888plaza.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE NORTHEAST =====
    {
        id: "greendale-plaza-l2",
        name: "Nursing Room at Greendale Plaza",
        venue: "Greendale Plaza",
        venueType: "mall",
        address: "298 Punggol Place, Singapore",
        postalCode: "820298",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.4010,
        longitude: 103.9040,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.greendaleplaza.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "anchorvale-community-club-l1",
        name: "Nursing Room at Anchorvale CC",
        venue: "Anchorvale Community Club",
        venueType: "community",
        address: "59 Anchorvale Road, Singapore",
        postalCode: "544964",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near main hall",
        latitude: 1.3935,
        longitude: 103.8855,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "09:00 - 22:00",
        sourceUrl1: "https://www.onepa.gov.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Community facility"
    },
    {
        id: "oasis-terraces-l2",
        name: "Nursing Room at Oasis Terraces",
        venue: "Oasis Terraces",
        venueType: "mall",
        address: "681 Punggol Drive, Singapore",
        postalCode: "820681",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near polyclinic",
        latitude: 1.4030,
        longitude: 103.9134,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.oasisterraces.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "buangkok-square-l2",
        name: "Nursing Room at Buangkok Square",
        venue: "Buangkok Square",
        venueType: "mall",
        address: "991 Buangkok Link, Singapore",
        postalCode: "530991",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3834,
        longitude: 103.8928,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.buangkoksquare.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE EAST =====
    {
        id: "ehub-downtown-east-l2",
        name: "Nursing Room at E!hub L2",
        venue: "E!hub @ Downtown East",
        venueType: "mall",
        address: "1 Pasir Ris Close, Singapore",
        postalCode: "519599",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near cinema",
        latitude: 1.3772,
        longitude: 103.9555,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.downtowneast.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "changi-city-point-l2",
        name: "Nursing Room at Changi City Point",
        venue: "Changi City Point",
        venueType: "mall",
        address: "5 Changi Business Park Central 1, Singapore",
        postalCode: "486038",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near food court",
        latitude: 1.3343,
        longitude: 103.9671,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.changicitypoint.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Business park mall"
    },
    {
        id: "loyang-point-l2",
        name: "Nursing Room at Loyang Point",
        venue: "Loyang Point",
        venueType: "mall",
        address: "259 Pasir Ris Street 21, Singapore",
        postalCode: "510259",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3684,
        longitude: 103.9616,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.loyangpoint.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "katong-i12-l2",
        name: "Nursing Room at i12 Katong",
        venue: "i12 Katong",
        venueType: "mall",
        address: "112 East Coast Road, Singapore",
        postalCode: "428802",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near cinema",
        latitude: 1.3049,
        longitude: 103.9047,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.i12katong.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Good family facilities"
    },
    {
        id: "katong-shopping-centre-l2",
        name: "Nursing Room at Katong Shopping Centre",
        venue: "Katong Shopping Centre",
        venueType: "mall",
        address: "865 Mountbatten Road, Singapore",
        postalCode: "437844",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.3039,
        longitude: 103.9026,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.katongsc.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "roxy-square-l2",
        name: "Nursing Room at Roxy Square",
        venue: "Roxy Square",
        venueType: "mall",
        address: "50 East Coast Road, Singapore",
        postalCode: "428769",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near toilet",
        latitude: 1.3051,
        longitude: 103.9023,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.roxysquare.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE HOSPITALS/CLINICS =====
    {
        id: "mount-alvernia-hospital-l1",
        name: "Nursing Room at Mount Alvernia Hospital",
        venue: "Mount Alvernia Hospital",
        venueType: "hospital",
        address: "820 Thomson Road, Singapore",
        postalCode: "574623",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main lobby",
        latitude: 1.3405,
        longitude: 103.8389,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.mtalvernia.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Catholic hospital"
    },
    {
        id: "parkway-east-hospital-l1",
        name: "Nursing Room at Parkway East Hospital",
        venue: "Parkway East Hospital",
        venueType: "hospital",
        address: "321 Joo Chiat Place, Singapore",
        postalCode: "427990",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near lobby",
        latitude: 1.3115,
        longitude: 103.9048,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.parkwayeast.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "raffles-hospital-l1",
        name: "Nursing Room at Raffles Hospital",
        venue: "Raffles Hospital",
        venueType: "hospital",
        address: "585 North Bridge Road, Singapore",
        postalCode: "188770",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near specialist clinic",
        latitude: 1.3012,
        longitude: 103.8560,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.raffleshospital.com",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "farrer-park-hospital-l1",
        name: "Nursing Room at Farrer Park Hospital",
        venue: "Farrer Park Hospital",
        venueType: "hospital",
        address: "1 Farrer Park Station Road, Singapore",
        postalCode: "217562",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near lobby",
        latitude: 1.3126,
        longitude: 103.8541,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.farrerpark.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Modern hospital"
    },
    {
        id: "khoo-teck-puat-hospital-l1",
        name: "Nursing Room at Khoo Teck Puat Hospital",
        venue: "Khoo Teck Puat Hospital",
        venueType: "hospital",
        address: "90 Yishun Central, Singapore",
        postalCode: "768828",
        region: "north",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main building",
        latitude: 1.4249,
        longitude: 103.8381,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink", "wheelchair_accessible"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.ktph.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "North region hospital"
    },
    {
        id: "changi-general-hospital-l1",
        name: "Nursing Room at Changi General Hospital",
        venue: "Changi General Hospital",
        venueType: "hospital",
        address: "2 Simei Street 3, Singapore",
        postalCode: "529889",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main building",
        latitude: 1.3405,
        longitude: 103.9493,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.cgh.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "East region hospital"
    },
    {
        id: "ng-teng-fong-hospital-l1",
        name: "Nursing Room at Ng Teng Fong General Hospital",
        venue: "Ng Teng Fong General Hospital",
        venueType: "hospital",
        address: "1 Jurong East Street 21, Singapore",
        postalCode: "609606",
        region: "west",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main building",
        latitude: 1.3337,
        longitude: 103.7468,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink", "wheelchair_accessible"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.ntfgh.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "West region hospital"
    },
    {
        id: "sengkang-general-hospital-l1",
        name: "Nursing Room at Sengkang General Hospital",
        venue: "Sengkang General Hospital",
        venueType: "hospital",
        address: "110 Sengkang East Way, Singapore",
        postalCode: "544886",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Main building",
        latitude: 1.3945,
        longitude: 103.8936,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink", "wheelchair_accessible"],
        openingHours: "24 hours",
        sourceUrl1: "https://www.skgh.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Northeast region hospital"
    },
    // ===== MORE MRT STATIONS =====
    {
        id: "mrt-bishan-b1",
        name: "Nursing Room at Bishan MRT",
        venue: "Bishan MRT Station",
        venueType: "transit",
        address: "200 Bishan Road, Singapore",
        postalCode: "579827",
        region: "central",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Paid area",
        latitude: 1.3505,
        longitude: 103.8485,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "NS/CC interchange"
    },
    {
        id: "mrt-harbourfront-b2",
        name: "Nursing Room at HarbourFront MRT",
        venue: "HarbourFront MRT Station",
        venueType: "transit",
        address: "1 Maritime Square, Singapore",
        postalCode: "099253",
        region: "central",
        areaAccess: "public",
        floorLevel: "B2",
        locationDetail: "Near exit D",
        latitude: 1.2654,
        longitude: 103.8213,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "NE/CC interchange"
    },
    {
        id: "mrt-dhoby-ghaut-b1",
        name: "Nursing Room at Dhoby Ghaut MRT",
        venue: "Dhoby Ghaut MRT Station",
        venueType: "transit",
        address: "11 Orchard Road, Singapore",
        postalCode: "238826",
        region: "central",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near exit B",
        latitude: 1.2994,
        longitude: 103.8456,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "NS/NE/CC interchange"
    },
    {
        id: "mrt-pasir-ris-l1",
        name: "Nursing Room at Pasir Ris MRT",
        venue: "Pasir Ris MRT Station",
        venueType: "transit",
        address: "10 Pasir Ris Central, Singapore",
        postalCode: "519634",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near exit A",
        latitude: 1.3732,
        longitude: 103.9494,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "EW terminus"
    },
    {
        id: "mrt-punggol-l1",
        name: "Nursing Room at Punggol MRT",
        venue: "Punggol MRT Station",
        venueType: "transit",
        address: "10 Punggol Central, Singapore",
        postalCode: "828851",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near exit B",
        latitude: 1.4052,
        longitude: 103.9024,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "NE terminus"
    },
    // ===== MORE ATTRACTIONS/MUSEUMS =====
    {
        id: "national-gallery-l1",
        name: "Nursing Room at National Gallery",
        venue: "National Gallery Singapore",
        venueType: "attraction",
        address: "1 St Andrew's Road, Singapore",
        postalCode: "178957",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2903,
        longitude: 103.8517,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.nationalgallery.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Art museum"
    },
    {
        id: "peranakan-museum-l1",
        name: "Nursing Room at Peranakan Museum",
        venue: "Peranakan Museum",
        venueType: "attraction",
        address: "39 Armenian Street, Singapore",
        postalCode: "179941",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2941,
        longitude: 103.8493,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.nhb.gov.sg/peranakanmuseum",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Heritage museum"
    },
    {
        id: "indian-heritage-centre-l1",
        name: "Nursing Room at Indian Heritage Centre",
        venue: "Indian Heritage Centre",
        venueType: "attraction",
        address: "5 Campbell Lane, Singapore",
        postalCode: "209924",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3062,
        longitude: 103.8522,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.indianheritage.org.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Little India"
    },
    {
        id: "malay-heritage-centre-l1",
        name: "Nursing Room at Malay Heritage Centre",
        venue: "Malay Heritage Centre",
        venueType: "attraction",
        address: "85 Sultan Gate, Singapore",
        postalCode: "198501",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3026,
        longitude: 103.8590,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 18:00",
        sourceUrl1: "https://www.malayheritage.org.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Kampong Glam"
    },
    {
        id: "chinatown-heritage-centre-l1",
        name: "Nursing Room at Chinatown Heritage Centre",
        venue: "Chinatown Heritage Centre",
        venueType: "attraction",
        address: "48 Pagoda Street, Singapore",
        postalCode: "059207",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2839,
        longitude: 103.8444,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "09:00 - 20:00",
        sourceUrl1: "https://www.chinatownheritagecentre.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "lee-kong-chian-museum-l1",
        name: "Nursing Room at Lee Kong Chian Natural History Museum",
        venue: "Lee Kong Chian Natural History Museum",
        venueType: "attraction",
        address: "2 Conservatory Drive, Singapore",
        postalCode: "117377",
        region: "west",
        areaAccess: "ticketed",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3006,
        longitude: 103.7736,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://lkcnhm.nus.edu.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "NUS museum, dinosaurs"
    },
    {
        id: "civil-defence-heritage-gallery-l1",
        name: "Nursing Room at Civil Defence Heritage Gallery",
        venue: "Civil Defence Heritage Gallery",
        venueType: "attraction",
        address: "62 Hill Street, Singapore",
        postalCode: "179367",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2931,
        longitude: 103.8494,
        features: ["breastfeeding_area", "changing_table"],
        openingHours: "10:00 - 17:00",
        sourceUrl1: "https://www.scdf.gov.sg/home/community-volunteers/cd-heritage-gallery",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Fire station history"
    },
];

export const seedDataPart3Count = SEED_DATA_PART3.length;
