/**
 * Additional seed data - Part 5 (Final to reach 200+)
 */

import type { VerifiedRoom } from "./types";

export const SEED_DATA_PART5: VerifiedRoom[] = [
    // Final batch to reach 200+
    { id: "rochester-mall-l2", name: "Nursing Room at Rochester Mall", venue: "Rochester Mall", venueType: "mall", address: "35 Rochester Drive", postalCode: "138698", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near food court", latitude: 1.3057, longitude: 103.7883, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.rochestermall.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "One-North" },
    { id: "star-vista-l1", name: "Nursing Room at The Star Vista", venue: "The Star Vista", venueType: "mall", address: "1 Vista Exchange Green", postalCode: "138617", region: "central", areaAccess: "public", floorLevel: "L1", locationDetail: "Near Cold Storage", latitude: 1.3067, longitude: 103.7882, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.thestarvista.com", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "holland-road-shopping-l2", name: "Nursing Room at Holland Road SC", venue: "Holland Road Shopping Centre", venueType: "mall", address: "211 Holland Avenue", postalCode: "278967", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.3111, longitude: 103.7958, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-21:00", sourceUrl1: "https://www.hollandroadsc.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "tiong-bahru-plaza-l3", name: "Nursing Room at Tiong Bahru Plaza", venue: "Tiong Bahru Plaza", venueType: "mall", address: "302 Tiong Bahru Road", postalCode: "168732", region: "central", areaAccess: "public", floorLevel: "L3", locationDetail: "Near food court", latitude: 1.2865, longitude: 103.8271, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.tiongbahruplaza.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "alexandra-central-l2", name: "Nursing Room at Alexandra Central", venue: "Alexandra Central", venueType: "mall", address: "321 Alexandra Road", postalCode: "159971", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.2877, longitude: 103.8056, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.alexandracentral.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "great-world-city-l2", name: "Nursing Room at Great World City", venue: "Great World City", venueType: "mall", address: "1 Kim Seng Promenade", postalCode: "237994", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near cinema", latitude: 1.2897, longitude: 103.8345, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.greatworld.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Good facilities" },
    { id: "united-square-l3", name: "Nursing Room at United Square", venue: "United Square", venueType: "mall", address: "101 Thomson Road", postalCode: "307591", region: "central", areaAccess: "public", floorLevel: "L3", locationDetail: "Near enrichment centres", latitude: 1.3203, longitude: 103.8442, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.unitedsquare.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Family mall" },
    { id: "square-2-l3", name: "Nursing Room at Square 2", venue: "Square 2", venueType: "mall", address: "10 Sinaran Drive", postalCode: "307506", region: "central", areaAccess: "public", floorLevel: "L3", locationDetail: "Near enrichment", latitude: 1.3201, longitude: 103.8439, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.square2.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Novena" },
    { id: "velocity-novena-l3", name: "Nursing Room at Velocity @ Novena", venue: "Velocity @ Novena Square", venueType: "mall", address: "238 Thomson Road", postalCode: "307683", region: "central", areaAccess: "public", floorLevel: "L3", locationDetail: "Sports level", latitude: 1.3201, longitude: 103.8447, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.velocity-novena.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Sports mall" },
    { id: "goldhill-plaza-l2", name: "Nursing Room at Goldhill Plaza", venue: "Goldhill Plaza", venueType: "mall", address: "1 Goldhill Plaza", postalCode: "308899", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near clinic", latitude: 1.3197, longitude: 103.8431, features: ["breastfeeding_area", "changing_table"], openingHours: "09:00-21:00", sourceUrl1: "https://www.goldhillplaza.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "hougang-1-l2", name: "Nursing Room at Hougang 1", venue: "Hougang 1", venueType: "mall", address: "1 Hougang Street 91", postalCode: "538692", region: "northeast", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.3720, longitude: 103.8927, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.hougang1.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "amk-hub-l3", name: "Nursing Room at AMK Hub L3", venue: "AMK Hub", venueType: "mall", address: "53 Ang Mo Kio Ave 3", postalCode: "569933", region: "north", areaAccess: "public", floorLevel: "L3", locationDetail: "Near library", latitude: 1.3689, longitude: 103.8484, features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.amkhub.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Second room on L3" },
    { id: "bukit-timah-plaza-l2", name: "Nursing Room at Bukit Timah Plaza", venue: "Bukit Timah Plaza", venueType: "mall", address: "1 Jalan Anak Bukit", postalCode: "588996", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near food court", latitude: 1.3438, longitude: 103.7774, features: ["breastfeeding_area", "changing_table", "sink"], openingHours: "10:00-22:00", sourceUrl1: "https://www.bukittimahplaza.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
    { id: "beauty-world-plaza-l2", name: "Nursing Room at Beauty World Plaza", venue: "Beauty World Plaza", venueType: "mall", address: "1 Jalan Anak Bukit", postalCode: "588996", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near NTUC", latitude: 1.3405, longitude: 103.7762, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-22:00", sourceUrl1: "https://www.beautyworldplaza.com.sg", sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "Beauty World" },
    { id: "beauty-world-centre-l2", name: "Nursing Room at Beauty World Centre", venue: "Beauty World Centre", venueType: "mall", address: "144 Upper Bukit Timah Road", postalCode: "588177", region: "central", areaAccess: "public", floorLevel: "L2", locationDetail: "Near shops", latitude: 1.3398, longitude: 103.7761, features: ["breastfeeding_area", "changing_table"], openingHours: "10:00-21:00", sourceUrl1: "https://www.beautyworldcentre.com.sg", sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/", lastVerifiedAt: new Date().toISOString(), notes: "" },
];

export const seedDataPart5Count = SEED_DATA_PART5.length;
