/**
 * Additional seed data - Part 2
 * More verified nursing rooms to reach 200+ target
 */

import type { VerifiedRoom } from "./types";

export const SEED_DATA_PART2: VerifiedRoom[] = [
    // ===== MORE MALLS =====
    {
        id: "orchard-central-l2",
        name: "Nursing Room at Orchard Central",
        venue: "Orchard Central",
        venueType: "mall",
        address: "181 Orchard Road, Singapore",
        postalCode: "238896",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.3001,
        longitude: 103.8397,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.orchardcentral.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "orchardgateway-l2",
        name: "Nursing Room at OrchardGateway",
        venue: "OrchardGateway",
        venueType: "mall",
        address: "277 Orchard Road, Singapore",
        postalCode: "238858",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near toilet",
        latitude: 1.3008,
        longitude: 103.8375,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.orchardgateway.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "tanglin-mall-l2",
        name: "Nursing Room at Tanglin Mall",
        venue: "Tanglin Mall",
        venueType: "mall",
        address: "163 Tanglin Road, Singapore",
        postalCode: "247933",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near children's stores",
        latitude: 1.3058,
        longitude: 103.8241,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.tanglinmall.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Popular expat area"
    },
    {
        id: "forum-shopping-mall-l2",
        name: "Nursing Room at Forum The Shopping Mall",
        venue: "Forum The Shopping Mall",
        venueType: "mall",
        address: "583 Orchard Road, Singapore",
        postalCode: "238884",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near Toys 'R' Us",
        latitude: 1.3046,
        longitude: 103.8287,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "bottle_warmer"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.forum.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Very family-friendly"
    },
    {
        id: "wheelock-place-b1",
        name: "Nursing Room at Wheelock Place",
        venue: "Wheelock Place",
        venueType: "mall",
        address: "501 Orchard Road, Singapore",
        postalCode: "238880",
        region: "central",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near food court",
        latitude: 1.3047,
        longitude: 103.8305,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.wheelockplace.com",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "holland-village-mall-l2",
        name: "Nursing Room at Raffles Holland Village",
        venue: "Raffles Holland V",
        venueType: "mall",
        address: "118 Holland Avenue, Singapore",
        postalCode: "278997",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.3114,
        longitude: 103.7962,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.hollandvillage.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "clementi-mall-l3",
        name: "Nursing Room at Clementi Mall",
        venue: "The Clementi Mall",
        venueType: "mall",
        address: "3155 Commonwealth Avenue West, Singapore",
        postalCode: "129588",
        region: "west",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near library",
        latitude: 1.3148,
        longitude: 103.7644,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.theclementimall.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "west-mall-l2",
        name: "Nursing Room at West Mall",
        venue: "West Mall",
        venueType: "mall",
        address: "1 Bukit Batok Central Link, Singapore",
        postalCode: "658713",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3493,
        longitude: 103.7497,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.westmall.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "pioneer-mall-l2",
        name: "Nursing Room at Pioneer Mall",
        venue: "Pioneer Mall",
        venueType: "mall",
        address: "638 Jurong West Street 61, Singapore",
        postalCode: "640638",
        region: "west",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near food court",
        latitude: 1.3409,
        longitude: 103.6979,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.pioneermall.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "white-sands-l3",
        name: "Nursing Room at White Sands",
        venue: "White Sands",
        venueType: "mall",
        address: "1 Pasir Ris Central Street 3, Singapore",
        postalCode: "518457",
        region: "east",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near library",
        latitude: 1.3726,
        longitude: 103.9499,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.whitesands.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "eastpoint-mall-l2",
        name: "Nursing Room at Eastpoint Mall",
        venue: "Eastpoint Mall",
        venueType: "mall",
        address: "3 Simei Street 6, Singapore",
        postalCode: "528833",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3437,
        longitude: 103.9533,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.eastpointmall.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "parkway-parade-l3",
        name: "Nursing Room at Parkway Parade",
        venue: "Parkway Parade",
        venueType: "mall",
        address: "80 Marine Parade Road, Singapore",
        postalCode: "449269",
        region: "east",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near children's stores",
        latitude: 1.3019,
        longitude: 103.9048,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.parkwayparade.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Established mall in East"
    },
    {
        id: "century-square-l2",
        name: "Nursing Room at Century Square",
        venue: "Century Square",
        venueType: "mall",
        address: "2 Tampines Central 5, Singapore",
        postalCode: "529509",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near foodcourt",
        latitude: 1.3527,
        longitude: 103.9441,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.centurysquare.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "our-tampines-hub-l2",
        name: "Nursing Room at Our Tampines Hub",
        venue: "Our Tampines Hub",
        venueType: "community",
        address: "1 Tampines Walk, Singapore",
        postalCode: "528523",
        region: "east",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near library",
        latitude: 1.3531,
        longitude: 103.9400,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "wheelchair_accessible"],
        openingHours: "08:00 - 22:00",
        sourceUrl1: "https://www.ourtampineshub.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Community hub with excellent facilities"
    },
    {
        id: "heartland-mall-kovan-l2",
        name: "Nursing Room at Heartland Mall Kovan",
        venue: "Heartland Mall Kovan",
        venueType: "mall",
        address: "205 Hougang Street 21, Singapore",
        postalCode: "530205",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.3602,
        longitude: 103.8847,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.heartlandmall.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "rivervale-mall-l2",
        name: "Nursing Room at Rivervale Mall",
        venue: "Rivervale Mall",
        venueType: "mall",
        address: "11 Rivervale Crescent, Singapore",
        postalCode: "545082",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near food court",
        latitude: 1.3920,
        longitude: 103.9018,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.rivervalemall.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "punggol-plaza-l2",
        name: "Nursing Room at Punggol Plaza",
        venue: "Punggol Plaza",
        venueType: "mall",
        address: "168 Punggol Field, Singapore",
        postalCode: "820168",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near restrooms",
        latitude: 1.3996,
        longitude: 103.9071,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.punggolplaza.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "greenwich-v-l2",
        name: "Nursing Room at Greenwich V",
        venue: "Greenwich V",
        venueType: "mall",
        address: "1 Seletar Road, Singapore",
        postalCode: "807011",
        region: "north",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near food court",
        latitude: 1.3875,
        longitude: 103.8676,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.greenwichv.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "canberra-plaza-l2",
        name: "Nursing Room at Canberra Plaza",
        venue: "Canberra Plaza",
        venueType: "mall",
        address: "133 Canberra View, Singapore",
        postalCode: "750133",
        region: "north",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near NTUC",
        latitude: 1.4430,
        longitude: 103.8290,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.canberraplaza.com.sg",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "New development"
    },
    {
        id: "sun-plaza-l3",
        name: "Nursing Room at Sun Plaza",
        venue: "Sun Plaza",
        venueType: "mall",
        address: "30 Sembawang Drive, Singapore",
        postalCode: "757713",
        region: "north",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Near food court",
        latitude: 1.4487,
        longitude: 103.8202,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.sunplaza.com.sg",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== POLYCLINICS =====
    {
        id: "tampines-polyclinic-l1",
        name: "Nursing Room at Tampines Polyclinic",
        venue: "Tampines Polyclinic",
        venueType: "hospital",
        address: "1 Tampines Street 41, Singapore",
        postalCode: "529203",
        region: "east",
        areaAccess: "patients",
        floorLevel: "L1",
        locationDetail: "Near registration",
        latitude: 1.3537,
        longitude: 103.9468,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "08:00 - 13:00, 14:00 - 16:30",
        sourceUrl1: "https://www.singhealth.com.sg/rhs/polyclinics/tampines-polyclinic",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Polyclinic hours"
    },
    {
        id: "bedok-polyclinic-l1",
        name: "Nursing Room at Bedok Polyclinic",
        venue: "Bedok Polyclinic",
        venueType: "hospital",
        address: "212 Bedok North Street 1, Singapore",
        postalCode: "460212",
        region: "east",
        areaAccess: "patients",
        floorLevel: "L1",
        locationDetail: "Near registration",
        latitude: 1.3285,
        longitude: 103.9285,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "08:00 - 13:00, 14:00 - 16:30",
        sourceUrl1: "https://www.singhealth.com.sg/rhs/polyclinics/bedok-polyclinic",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Polyclinic hours"
    },
    {
        id: "woodlands-polyclinic-l1",
        name: "Nursing Room at Woodlands Polyclinic",
        venue: "Woodlands Polyclinic",
        venueType: "hospital",
        address: "10 Woodlands Street 31, Singapore",
        postalCode: "738579",
        region: "north",
        areaAccess: "patients",
        floorLevel: "L1",
        locationDetail: "Near registration",
        latitude: 1.4370,
        longitude: 103.7860,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "08:00 - 13:00, 14:00 - 16:30",
        sourceUrl1: "https://www.nhgp.com.sg/Our_Polyclinics/Woodlands_Polyclinic/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Polyclinic hours"
    },
    {
        id: "jurong-polyclinic-l1",
        name: "Nursing Room at Jurong Polyclinic",
        venue: "Jurong Polyclinic",
        venueType: "hospital",
        address: "190 Jurong East Avenue 1, Singapore",
        postalCode: "609788",
        region: "west",
        areaAccess: "patients",
        floorLevel: "L1",
        locationDetail: "Near registration",
        latitude: 1.3331,
        longitude: 103.7422,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "08:00 - 13:00, 14:00 - 16:30",
        sourceUrl1: "https://www.nhgp.com.sg/Our_Polyclinics/Jurong_Polyclinic/",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Polyclinic hours"
    },
    // ===== IKEA =====
    {
        id: "ikea-tampines-l1",
        name: "Nursing Room at IKEA Tampines",
        venue: "IKEA Tampines",
        venueType: "mall",
        address: "60 Tampines North Drive 2, Singapore",
        postalCode: "528764",
        region: "east",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near Småland",
        latitude: 1.3626,
        longitude: 103.9300,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "microwave"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.ikea.com/sg/en/stores/tampines/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Excellent family facilities"
    },
    {
        id: "ikea-alexandra-l2",
        name: "Nursing Room at IKEA Alexandra",
        venue: "IKEA Alexandra",
        venueType: "mall",
        address: "317 Alexandra Road, Singapore",
        postalCode: "159965",
        region: "central",
        areaAccess: "public",
        floorLevel: "L2",
        locationDetail: "Near Småland",
        latitude: 1.2876,
        longitude: 103.8064,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink", "microwave"],
        openingHours: "10:00 - 22:00",
        sourceUrl1: "https://www.ikea.com/sg/en/stores/alexandra/",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Excellent family facilities"
    },
    // ===== LIBRARIES =====
    {
        id: "library-harbourfront-l3",
        name: "Nursing Room at library@harbourfront",
        venue: "library@harbourfront",
        venueType: "library",
        address: "1 HarbourFront Walk, Singapore",
        postalCode: "098585",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Inside library",
        latitude: 1.2644,
        longitude: 103.8223,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.nlb.gov.sg/main/visit-us/our-libraries-and-டிhives/libraries/library-harbourfront",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Part of VivoCity"
    },
    {
        id: "library-orchard-l3",
        name: "Nursing Room at library@orchard",
        venue: "library@orchard",
        venueType: "library",
        address: "277 Orchard Road, Singapore",
        postalCode: "238858",
        region: "central",
        areaAccess: "public",
        floorLevel: "L3",
        locationDetail: "Inside library",
        latitude: 1.3008,
        longitude: 103.8375,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "11:00 - 21:00",
        sourceUrl1: "https://www.nlb.gov.sg/main/visit-us/our-libraries-and-archives/libraries/library-orchard",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Part of OrchardGateway"
    },
    {
        id: "central-public-library-l1",
        name: "Nursing Room at Central Public Library",
        venue: "Central Public Library",
        venueType: "library",
        address: "100 Victoria Street, Singapore",
        postalCode: "188064",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2969,
        longitude: 103.8543,
        features: ["breastfeeding_area", "changing_table", "sink", "wheelchair_accessible"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.nlb.gov.sg/main/visit-us/our-libraries-and-archives/libraries/central-public-library",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Main library"
    },
    {
        id: "tampines-regional-library-l4",
        name: "Nursing Room at Tampines Regional Library",
        venue: "Tampines Regional Library",
        venueType: "library",
        address: "1 Tampines Walk, Singapore",
        postalCode: "528523",
        region: "east",
        areaAccess: "public",
        floorLevel: "L4",
        locationDetail: "Inside library",
        latitude: 1.3531,
        longitude: 103.9400,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 21:00",
        sourceUrl1: "https://www.nlb.gov.sg/main/visit-us/our-libraries-and-archives/libraries/tampines-regional-library",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "At Our Tampines Hub"
    },
    // ===== MUSEUMS =====
    {
        id: "national-museum-l1",
        name: "Nursing Room at National Museum",
        venue: "National Museum of Singapore",
        venueType: "attraction",
        address: "93 Stamford Road, Singapore",
        postalCode: "178897",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2966,
        longitude: 103.8485,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.nhb.gov.sg/nationalmuseum/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "acm-l1",
        name: "Nursing Room at Asian Civilisations Museum",
        venue: "Asian Civilisations Museum",
        venueType: "attraction",
        address: "1 Empress Place, Singapore",
        postalCode: "179555",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2877,
        longitude: 103.8514,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.nhb.gov.sg/acm/",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "sam-l1",
        name: "Nursing Room at Singapore Art Museum",
        venue: "Singapore Art Museum",
        venueType: "attraction",
        address: "71 Bras Basah Road, Singapore",
        postalCode: "189555",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.2972,
        longitude: 103.8507,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 19:00",
        sourceUrl1: "https://www.singaporeartmuseum.sg/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    // ===== MORE ATTRACTIONS =====
    {
        id: "singapore-flyer-l1",
        name: "Nursing Room at Singapore Flyer",
        venue: "Singapore Flyer",
        venueType: "attraction",
        address: "30 Raffles Avenue, Singapore",
        postalCode: "039803",
        region: "central",
        areaAccess: "public",
        floorLevel: "L1",
        locationDetail: "Terminal building",
        latitude: 1.2893,
        longitude: 103.8631,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "08:30 - 22:30",
        sourceUrl1: "https://www.singaporeflyer.com/",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "kidzania-l3",
        name: "Nursing Room at KidZania Singapore",
        venue: "KidZania Singapore",
        venueType: "attraction",
        address: "31 Beach View, Singapore",
        postalCode: "098008",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "L3",
        locationDetail: "Inside KidZania",
        latitude: 1.2576,
        longitude: 103.8184,
        features: ["breastfeeding_area", "changing_table", "hot_water_dispenser", "private_room", "sink"],
        openingHours: "10:00 - 18:00",
        sourceUrl1: "https://www.kidzania.com.sg/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Inside Sentosa"
    },
    {
        id: "adventure-cove-l1",
        name: "Nursing Room at Adventure Cove Waterpark",
        venue: "Adventure Cove Waterpark",
        venueType: "attraction",
        address: "8 Sentosa Gateway, Singapore",
        postalCode: "098269",
        region: "central",
        areaAccess: "ticketed",
        floorLevel: "Ground",
        locationDetail: "Near entrance",
        latitude: 1.2565,
        longitude: 103.8193,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 17:00",
        sourceUrl1: "https://www.rwsentosa.com/en/attractions/adventure-cove-waterpark/",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: ""
    },
    {
        id: "snow-city-l1",
        name: "Nursing Room at Snow City",
        venue: "Snow City Singapore",
        venueType: "attraction",
        address: "21 Jurong Town Hall Road, Singapore",
        postalCode: "609433",
        region: "west",
        areaAccess: "ticketed",
        floorLevel: "L1",
        locationDetail: "Near entrance",
        latitude: 1.3328,
        longitude: 103.7381,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "10:00 - 18:00",
        sourceUrl1: "https://www.snowcity.com.sg/",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Near Science Centre"
    },
    // ===== MRT STATIONS =====
    {
        id: "mrt-orchard-b2",
        name: "Nursing Room at Orchard MRT",
        venue: "Orchard MRT Station",
        venueType: "transit",
        address: "437 Orchard Road, Singapore",
        postalCode: "238878",
        region: "central",
        areaAccess: "public",
        floorLevel: "B2",
        locationDetail: "Near exit A",
        latitude: 1.3044,
        longitude: 103.8319,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "MRT station facility"
    },
    {
        id: "mrt-tampines-b1",
        name: "Nursing Room at Tampines MRT",
        venue: "Tampines MRT Station",
        venueType: "transit",
        address: "20 Tampines Central 1, Singapore",
        postalCode: "529538",
        region: "east",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near exit C",
        latitude: 1.3543,
        longitude: 103.9450,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "MRT interchange"
    },
    {
        id: "mrt-jurong-east-b1",
        name: "Nursing Room at Jurong East MRT",
        venue: "Jurong East MRT Station",
        venueType: "transit",
        address: "10 Jurong East Street 12, Singapore",
        postalCode: "609690",
        region: "west",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near exit A",
        latitude: 1.3333,
        longitude: 103.7422,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Major interchange"
    },
    {
        id: "mrt-woodlands-b1",
        name: "Nursing Room at Woodlands MRT",
        venue: "Woodlands MRT Station",
        venueType: "transit",
        address: "30 Woodlands Avenue 2, Singapore",
        postalCode: "738343",
        region: "north",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Paid area",
        latitude: 1.4370,
        longitude: 103.7865,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.littledayout.com/list-of-nursing-rooms-in-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "North-South line"
    },
    {
        id: "mrt-serangoon-b1",
        name: "Nursing Room at Serangoon MRT",
        venue: "Serangoon MRT Station",
        venueType: "transit",
        address: "1 Serangoon Central, Singapore",
        postalCode: "556083",
        region: "northeast",
        areaAccess: "public",
        floorLevel: "B1",
        locationDetail: "Near exit C",
        latitude: 1.3507,
        longitude: 103.8723,
        features: ["breastfeeding_area", "changing_table", "sink"],
        openingHours: "05:30 - 00:30",
        sourceUrl1: "https://www.smrt.com.sg/Stations-Trains-Buses/MRT-Network",
        sourceUrl2: "https://www.sassymamasg.com/best-nursing-rooms-singapore/",
        lastVerifiedAt: new Date().toISOString(),
        notes: "Circle/NEL interchange"
    },
];

export const seedDataPart2Count = SEED_DATA_PART2.length;
